services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=hermes
      - POSTGRES_PASSWORD=hermes
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: